include $(APPDIR)/Make.defs

# FreeModBus demo built-in application info

PROGNAME = modbus_tcp
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_MODBUS)

# FreeModBus demo

MAINSRC = modbus_main.c

include $(APPDIR)/Application.mk